export const PLAYER_FREEZE_TIME = 500;
export const OBJECTS_GENERATION_TIME = 1000;
export const OBJECTS_UPDATE_TIME = 800;
export const MINIMUM_OF_OBSTACLES = 12;
export const MAXIMUM_OF_OBSTACLES = MINIMUM_OF_OBSTACLES + 8;
